POST http://localhost:5001/post
Content-Type: application/json

{
    "postContent": "Test Post!",
    "username": "Mike"
}

###

GET http://localhost:5001/auth/login
Content-Type: application/json

{
    "username":"Mike",
    "password":"Test password"
}