GET http://localhost:5001/api/post
Content-Type: application/json

{
    "username": "Tommi"
}

###

POST http://localhost:5001/api/post
Content-Type: application/json

{
    "username": "Tomi",
    "postText": "Second Test Post"
}

###
DELETE http://localhost:5001/api/post
Content-Type: application/json

{
    "postID": "698fa25d6adfe4b30e1d3152"
}
###
PUT http://localhost:5001/api/post
Content-Type: application/json

{
    "postID": "698fa5712b6c97fe0f749051",
    "username": "Tommy",
    "postText": "Updated Post"
}

