GET http://localhost:5001/api/post
Content-Type: application/json

{
    "username": "Tommi"
}

###

POST http://localhost:5001/api/post
Content-Type: application/json

{
    "username": "Tomi",
    "postText": "Posty McPostFace"
}

###
DELETE http://localhost:5001/api/post
Content-Type: application/json

{
    "postID": "698fa25d6adfe4b30e1d3152"
}
###
PUT http://localhost:5001/api/post
Content-Type: application/json

{
    "postID": "698fa5712b6c97fe0f749051",
    "username": "Tommy",
    "postText": "Updated Post"
}

###
GET http://localhost:5001/api/post/user/?user=Tomi
Content-Type: application/json

{
    
}

###
POST http://localhost:5001/api/auth
Content-Type: application/json

{
    "username":"Yugi Moto",
    "password":"testpassword"
}
###
GET http://localhost:5001/api/auth
Content-Type: application/json

{
    
}
###
DELETE http://localhost:5001/api/auth
Content-Type: application/json

{
    "username":"Yugi Moto"
}